Part.create(name: "Hardrock", manufacturer: "Specialized", component: "frame", weight: 695)
Part.create(name: "Rockhopper", manufacturer: "Specialized", component: "frame", weight: 657)
Part.create(name: "Epic", manufacturer: "Specialized", component: "frame", weight: 701)
Part.create(name: "Carbon Nomad", manufacturer: "Santa Cruz", component: "frame", weight: 655)
Part.create(name: "Float 100", manufacturer: "Fox", component: "fork", weight: 437)
Part.create(name: "Float 120", manufacturer: "Fox", component: "fork", weight: 465)
Part.create(name: "Revelation", manufacturer: "Rock Shox", component: "fork", weight: 695)
Part.create(name: "Spinners", manufacturer: "Spinnin Rims", component: "wheelset", weight: 1280)
Part.create(name: "Arch", manufacturer: "Stan's", component: "wheelset", weight: 1123)
Part.create(name: "Float", manufacturer: "Stan's", component: "wheelset", weight: 1046)
Part.create(name: "Sickgrips", manufacturer: "Satan", component: "handlebars", weight: 100)
Part.create(name: "HellStem", manufacturer: "Satan", component: "stem", weight: 50)
Part.create(name: "BigSeat", manufacturer: "Big Bikes for Big People", component: "seat", weight: 250)
Part.create(name: "ObesityKeeper", manufacturer: "McBike", component: "seatpost", weight: 250)
Part.create(name: "Stoppers", manufacturer: "CHINA", component: "brakes", weight: 1899)